---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: fibonacci
  name: fibonacci
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fibonacci
  name: fibonacci
  namespace: fibonacci
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fibonacci
  template:
    metadata:
      labels:
        app: fibonacci
    spec:
#      runtimeClassName: gvisor
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
#        appArmorProfile:
#          type: Localhost
#          localhostProfile: k8s-apparmor-example-for-fibonacci
      containers:
      - image: fibonacci:0
        name: fibonacci
        ports:
        - containerPort: 8000
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          readOnlyRootFilesystem: true
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fibonacci
  namespace: fibonacci
spec:
  podSelector: {}
  policyTypes:
  - Egress
  - Ingress
  egress:
  - {}
  ingress:
  - ports:
    - protocol: TCP
      port: 8000
